//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Info.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        public int Book_id { get; set; }
        public string Book_name { get; set; }
        public string Author { get; set; }
        public string Publication { get; set; }
        public string subject { get; set; }
    }
}
